language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp grunt-cli
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: Zgy/ndjGdw8lpOzmnaC/SOzKR7lv4Rrk7luS4hVwGw8WtvPH3xO42MMTAVGeun8MpscXvPVl513ww0i868y8o/1W9x5ize9sUcAaLRdzLmD5RI3uspXBekEyHt4HitiyXp8mU7WI/shD6z1Lfzqv/fdRb9V4LKGS3TaFdlpVmS8=
  on:
    tags: true
    repo: T1st3/vendor-icons
